Update hero block images for all newsletters
parameter1/randall-reilly-newsletters pull request #24
Opened 2021-07-08 13:42 UTC by Shinsina

<img width="1792" alt="Screen Shot 2021-07-08 at 8 41 28 AM" src="https://user-images.githubusercontent.com/46794001/124931969-4cceb300-dfc8-11eb-8f4a-a8f74ea74675.png">
<img width="1792" alt="Screen Shot 2021-07-08 at 8 41 39 AM" src="https://user-images.githubusercontent.com/46794001/124931993-522bfd80-dfc8-11eb-990d-8d8d9b15c1f1.png">
This discludes the images for the first hero block on all newsletters except OVD Custom Rigs.

2021-07-08 13:42 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update newsletter templates to use the "No Hero" variation as the default](https://trello.com/c/bTauFcfh/70-update-newsletter-templates-to-use-the-no-hero-variation-as-the-default)

2021-07-08 13:51 UTC, brandonbk requested changes
@Shinsina - 

Today they only want the top story image for Custom Rigs newsletter, but that could change down the road to include others.  It would be better to make this more generic.

I would advise the following:
- Change the ovd-custom-rigs.marko template to something like  `<common-weekly-layout data=data top-story-image=true />`
- Update the weekly and daily layouts to support the `topStoryImage` parameter, with a default value of `false`

This approach makes it much more future-proof, and puts the customization within the actual template that is requesting it.

2021-07-09 14:55 UTC, brandonbk approved these changes

2021-07-09 14:55 UTC, brandonbk approved these changes

2021-07-09 14:55 UTC, merged